use crate::patterns::vuln_rules::*;

// ========================== PYTHON ==========================
pub static PYTHON_RULES: &[VulnRule] = &[
    VulnRule {
        id: "PY-INJ-001",
        name: "SQL Injection (Python)",
        description: "String formatting/concatenation in SQL query — classic SQLi vector",
        category: VulnCategory::Injection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:execute|cursor\.execute|\.raw|\.extra)\s*\(\s*(?:f["\']|["\'].*%s|["\'].*\bformat\b|["\'].*\+)"#,
        languages: &["py"],
        cwe: "CWE-89",
        remediation: "Use parameterized queries with placeholders",
        false_positive_hint: "Check if the string is a constant or properly parameterized",
    },
    VulnRule {
        id: "PY-INJ-002",
        name: "Command Injection (Python)",
        description: "User input passed to shell command execution",
        category: VulnCategory::CommandInjection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:os\.system|os\.popen|subprocess\.call|subprocess\.Popen|subprocess\.run|commands\.getoutput)\s*\(\s*(?:f["\']|.*\+|.*%|.*\.format)"#,
        languages: &["py"],
        cwe: "CWE-78",
        remediation: "Use subprocess with shell=False and list arguments",
        false_positive_hint: "Verify if input is user-controlled",
    },
    VulnRule {
        id: "PY-INJ-003",
        name: "Code Injection via eval/exec (Python)",
        description: "Dynamic code execution — potential RCE",
        category: VulnCategory::Injection,
        severity: Severity::Critical,
        pattern: r#"(?i)\b(?:eval|exec|compile)\s*\([^)]*(?:request|input|argv|args|param|data|user|query|payload|body)"#,
        languages: &["py"],
        cwe: "CWE-94",
        remediation: "Never pass user input to eval/exec. Use ast.literal_eval for safe parsing",
        false_positive_hint: "Check if the argument is a constant",
    },
    VulnRule {
        id: "PY-DESER-001",
        name: "Insecure Deserialization (Python pickle)",
        description: "Pickle/marshal/shelve loading untrusted data — RCE vector",
        category: VulnCategory::InsecureDeserialization,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:pickle\.loads?|cPickle\.loads?|marshal\.loads?|shelve\.open|yaml\.(?:unsafe_load|load\s*\())"#,
        languages: &["py"],
        cwe: "CWE-502",
        remediation: "Use yaml.safe_load(), avoid pickle on untrusted data",
        false_positive_hint: "Check if data source is trusted",
    },
    VulnRule {
        id: "PY-PATH-001",
        name: "Path Traversal (Python)",
        description: "User input in file path without sanitization",
        category: VulnCategory::PathTraversal,
        severity: Severity::High,
        pattern: r#"(?i)(?:open|Path)\s*\(\s*(?:f["\']|.*\+|.*%|.*\.format|.*os\.path\.join)\s*.*(?:request|input|argv|param|filename|user)"#,
        languages: &["py"],
        cwe: "CWE-22",
        remediation: "Validate and sanitize file paths, use os.path.realpath and check prefix",
        false_positive_hint: "Check if path is validated against a base directory",
    },
    VulnRule {
        id: "PY-SSRF-001",
        name: "SSRF (Python)",
        description: "User-controlled URL in HTTP request — SSRF vector",
        category: VulnCategory::SSRF,
        severity: Severity::High,
        pattern: r#"(?i)(?:requests\.(?:get|post|put|delete|patch|head)|urllib\.request\.urlopen|urllib2\.urlopen|httpx\.\w+|aiohttp\.\w+\.(?:get|post))\s*\(\s*(?:f["\']|.*\+|.*%|.*format|.*request|.*input|.*param|.*user|.*url)"#,
        languages: &["py"],
        cwe: "CWE-918",
        remediation: "Validate and whitelist URLs, block internal IP ranges",
        false_positive_hint: "Check if URL is user-controlled",
    },
    VulnRule {
        id: "PY-XSS-001",
        name: "XSS via Template (Python)",
        description: "Unescaped output in Jinja2/Django template or mark_safe",
        category: VulnCategory::XSS,
        severity: Severity::High,
        pattern: r#"(?i)(?:\|\s*safe\b|mark_safe\s*\(|Markup\s*\(|{% autoescape\s+off|\.format\(.*request\.|render_template_string)"#,
        languages: &["py", "html"],
        cwe: "CWE-79",
        remediation: "Use auto-escaping, avoid mark_safe with user input",
        false_positive_hint: "Check if content is from a trusted source",
    },
    VulnRule {
        id: "PY-CRYPTO-001",
        name: "Weak Cryptography (Python)",
        description: "Use of broken crypto algorithms (MD5/SHA1 for security, DES, RC4)",
        category: VulnCategory::WeakCrypto,
        severity: Severity::Medium,
        pattern: r#"(?i)(?:hashlib\.(?:md5|sha1)\s*\(|DES\.new|ARC4\.new|Blowfish\.new|\.pbkdf2_hmac\s*\(\s*["\'](?:md5|sha1))"#,
        languages: &["py"],
        cwe: "CWE-327",
        remediation: "Use SHA-256+ for hashing, AES-GCM for encryption",
        false_positive_hint: "MD5/SHA1 for checksums (non-security) is acceptable",
    },
    VulnRule {
        id: "PY-RAND-001",
        name: "Insecure Random (Python)",
        description: "Using random module for security-sensitive operations",
        category: VulnCategory::InsecureRandom,
        severity: Severity::Medium,
        pattern: r#"(?i)\brandom\.(?:random|randint|choice|randrange|shuffle)\s*\(.*(?:token|secret|password|key|session|nonce|salt|otp|pin)"#,
        languages: &["py"],
        cwe: "CWE-330",
        remediation: "Use secrets module or os.urandom() for security purposes",
        false_positive_hint: "Check if used in security context",
    },
    VulnRule {
        id: "PY-XXE-001",
        name: "XXE via XML Parsing (Python)",
        description: "XML parser without disabling external entities",
        category: VulnCategory::XXE,
        severity: Severity::High,
        pattern: r#"(?i)(?:etree\.parse|minidom\.parse|xml\.sax\.parse|etree\.fromstring|XMLParser)\s*\("#,
        languages: &["py"],
        cwe: "CWE-611",
        remediation: "Use defusedxml library or disable external entity resolution",
        false_positive_hint: "Check if defusedxml is imported or entities are disabled",
    },
    VulnRule {
        id: "PY-TMPL-001",
        name: "Server-Side Template Injection (Python)",
        description: "User input rendered in template string — SSTI / RCE",
        category: VulnCategory::TemplateInjection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:render_template_string|Template\s*\(|Environment\s*\(.*\)\.from_string)\s*\(.*(?:request|input|param|user|data|body)"#,
        languages: &["py"],
        cwe: "CWE-1336",
        remediation: "Never pass user input directly into template rendering",
        false_positive_hint: "Verify if user input reaches the template string",
    },
    VulnRule {
        id: "PY-LDAP-001",
        name: "LDAP Injection (Python)",
        description: "User input in LDAP query without escaping",
        category: VulnCategory::LDAPInjection,
        severity: Severity::High,
        pattern: r#"(?i)(?:ldap\.search_s|search_s|ldap_search)\s*\(.*(?:f["\']|\.format|%s|\+\s*(?:request|input|user|param))"#,
        languages: &["py"],
        cwe: "CWE-90",
        remediation: "Use ldap.filter.escape_filter_chars() on user input",
        false_positive_hint: "Check if input is properly escaped",
    },
];

// ========================== JAVASCRIPT / TYPESCRIPT ==========================
pub static JS_RULES: &[VulnRule] = &[
    VulnRule {
        id: "JS-INJ-001",
        name: "SQL Injection (JavaScript)",
        description: "String concatenation/template literal in SQL query",
        category: VulnCategory::Injection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:\.query|\.execute|\.raw)\s*\(\s*(?:`[^`]*\$\{|["\'].*\+|["\'].*concat)"#,
        languages: &["js", "ts", "jsx", "tsx"],
        cwe: "CWE-89",
        remediation: "Use parameterized queries or prepared statements",
        false_positive_hint: "Check if using ORM parameterization",
    },
    VulnRule {
        id: "JS-INJ-002",
        name: "NoSQL Injection (JavaScript)",
        description: "User input directly in MongoDB/NoSQL query operator",
        category: VulnCategory::Injection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:\.find|\.findOne|\.update|\.delete|\.aggregate|\.where)\s*\(\s*(?:\{[^}]*(?:req\.(?:body|query|params)|request\.|input)|JSON\.parse)"#,
        languages: &["js", "ts"],
        cwe: "CWE-943",
        remediation: "Validate and sanitize input, use mongoose schema validation",
        false_positive_hint: "Check if input is validated before query",
    },
    VulnRule {
        id: "JS-XSS-001",
        name: "DOM XSS (JavaScript)",
        description: "Direct DOM manipulation with unsanitized input",
        category: VulnCategory::XSS,
        severity: Severity::High,
        pattern: r#"(?i)(?:\.innerHTML|\.outerHTML|document\.write|document\.writeln|\.insertAdjacentHTML)\s*(?:=|\()\s*(?:[^;]*(?:location|document\.URL|document\.referrer|window\.name|\.value|\.search|\.hash|req\.|request\.|param|user|input|data))"#,
        languages: &["js", "ts", "jsx", "tsx", "html"],
        cwe: "CWE-79",
        remediation: "Use textContent instead of innerHTML, sanitize with DOMPurify",
        false_positive_hint: "Check if input is sanitized before insertion",
    },
    VulnRule {
        id: "JS-XSS-002",
        name: "React dangerouslySetInnerHTML",
        description: "Using dangerouslySetInnerHTML with user-controlled content",
        category: VulnCategory::XSS,
        severity: Severity::High,
        pattern: r#"(?i)dangerouslySetInnerHTML\s*=\s*\{\s*\{\s*__html\s*:"#,
        languages: &["js", "ts", "jsx", "tsx"],
        cwe: "CWE-79",
        remediation: "Sanitize HTML with DOMPurify before using dangerouslySetInnerHTML",
        false_positive_hint: "Check if the HTML is sanitized",
    },
    VulnRule {
        id: "JS-CMD-001",
        name: "Command Injection (JavaScript)",
        description: "User input in shell command execution",
        category: VulnCategory::CommandInjection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:child_process\.exec\s*\(|execSync\s*\(|spawn\s*\(\s*["\'](?:sh|bash|cmd)|\.exec\s*\()\s*(?:`[^`]*\$\{|["\'].*\+|.*req\.|.*request\.|.*input|.*param|.*user)"#,
        languages: &["js", "ts"],
        cwe: "CWE-78",
        remediation: "Use execFile/spawn with array arguments, never shell=true with user input",
        false_positive_hint: "Verify if input is user-controlled",
    },
    VulnRule {
        id: "JS-PROTO-001",
        name: "Prototype Pollution (JavaScript)",
        description: "Unsafe deep merge/extend/assign with user input",
        category: VulnCategory::PrototypePollution,
        severity: Severity::High,
        pattern: r#"(?i)(?:(?:deep)?[Mm]erge|extend|assign|defaults(?:Deep)?)\s*\([^)]*(?:req\.body|req\.query|req\.params|request\.|input|user|JSON\.parse)"#,
        languages: &["js", "ts"],
        cwe: "CWE-1321",
        remediation: "Validate keys, reject __proto__, constructor, prototype",
        false_positive_hint: "Check if keys are validated",
    },
    VulnRule {
        id: "JS-DESER-001",
        name: "Insecure Deserialization (JavaScript)",
        description: "Deserializing untrusted data (node-serialize, js-yaml)",
        category: VulnCategory::InsecureDeserialization,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:(?:node-serialize|serialize-javascript).*\.unserialize|yaml\.load\s*\(|\.deserialize\s*\()\s*.*(?:req\.|request\.|input|user|body|data|param)"#,
        languages: &["js", "ts"],
        cwe: "CWE-502",
        remediation: "Never deserialize untrusted data, use JSON.parse with schema validation",
        false_positive_hint: "Check data source",
    },
    VulnRule {
        id: "JS-SSRF-001",
        name: "SSRF (JavaScript)",
        description: "User-controlled URL passed to HTTP client",
        category: VulnCategory::SSRF,
        severity: Severity::High,
        pattern: r#"(?i)(?:axios|fetch|got|request|superagent|node-fetch|undici)\s*(?:\(|\.(?:get|post|put|delete))\s*\(\s*(?:`[^`]*\$\{|.*\+|.*req\.|.*request\.|.*param|.*user|.*input|.*url)"#,
        languages: &["js", "ts"],
        cwe: "CWE-918",
        remediation: "Validate and whitelist URLs, block internal IP ranges",
        false_positive_hint: "Check if URL is user-controlled",
    },
    VulnRule {
        id: "JS-PATH-001",
        name: "Path Traversal (JavaScript)",
        description: "User input in file path operations",
        category: VulnCategory::PathTraversal,
        severity: Severity::High,
        pattern: r#"(?i)(?:fs\.(?:readFile|writeFile|access|stat|unlink|readdir|createReadStream|createWriteStream)(?:Sync)?|path\.(?:join|resolve))\s*\(.*(?:req\.|request\.|param|user|input|body|query)"#,
        languages: &["js", "ts"],
        cwe: "CWE-22",
        remediation: "Validate paths, resolve and check they're within allowed directory",
        false_positive_hint: "Check if path is validated against base directory",
    },
    VulnRule {
        id: "JS-EVAL-001",
        name: "Code Injection via eval (JavaScript)",
        description: "Dynamic code execution with user input",
        category: VulnCategory::Injection,
        severity: Severity::Critical,
        pattern: r#"(?i)\b(?:eval|Function|setTimeout|setInterval)\s*\(\s*(?:[^)]*(?:req\.|request\.|input|user|param|data|body|query)|`)"#,
        languages: &["js", "ts"],
        cwe: "CWE-94",
        remediation: "Never use eval with user input. Use safe alternatives",
        false_positive_hint: "Check if argument is user-controlled",
    },
    VulnRule {
        id: "JS-REDIRECT-001",
        name: "Open Redirect (JavaScript)",
        description: "User-controlled redirect URL",
        category: VulnCategory::OpenRedirect,
        severity: Severity::Medium,
        pattern: r#"(?i)(?:res\.redirect|window\.location|location\.href|location\.assign|location\.replace)\s*(?:=|\()\s*(?:req\.|request\.|param|user|input|query|url)"#,
        languages: &["js", "ts"],
        cwe: "CWE-601",
        remediation: "Validate redirect URLs against a whitelist of allowed destinations",
        false_positive_hint: "Check if URL is validated",
    },
    VulnRule {
        id: "JS-REGEX-001",
        name: "ReDoS - Regular Expression DoS (JavaScript)",
        description: "Regex pattern vulnerable to catastrophic backtracking",
        category: VulnCategory::RegexDoS,
        severity: Severity::Medium,
        pattern: r#"(?:new RegExp|\.match|\.test|\.replace)\s*\(\s*(?:req\.|request\.|input|user|param|body|query)"#,
        languages: &["js", "ts"],
        cwe: "CWE-1333",
        remediation: "Validate regex input, use safe-regex or re2",
        false_positive_hint: "Check if regex pattern is user-controlled",
    },
];

// ========================== JAVA ==========================
pub static JAVA_RULES: &[VulnRule] = &[
    VulnRule {
        id: "JAVA-INJ-001",
        name: "SQL Injection (Java)",
        description: "String concatenation in SQL statement",
        category: VulnCategory::Injection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:Statement|createStatement|prepareStatement|createQuery|createNativeQuery|jdbcTemplate\.(?:query|update|execute))\s*(?:\(|\.).*(?:\+\s*|"\s*\+\s*)"#,
        languages: &["java"],
        cwe: "CWE-89",
        remediation: "Use PreparedStatement with parameterized queries",
        false_positive_hint: "Check if PreparedStatement placeholders are used",
    },
    VulnRule {
        id: "JAVA-INJ-002",
        name: "Command Injection (Java)",
        description: "User input in runtime exec",
        category: VulnCategory::CommandInjection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:Runtime\.getRuntime\(\)\.exec|ProcessBuilder|new\s+ProcessBuilder)\s*\(.*(?:\+|concat|request|param|input|user|getParameter)"#,
        languages: &["java"],
        cwe: "CWE-78",
        remediation: "Use ProcessBuilder with explicit command array, never concat user input",
        false_positive_hint: "Check if input is user-controlled",
    },
    VulnRule {
        id: "JAVA-DESER-001",
        name: "Insecure Deserialization (Java)",
        description: "ObjectInputStream.readObject() on untrusted data — RCE gadget chains",
        category: VulnCategory::InsecureDeserialization,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:ObjectInputStream|\.readObject\s*\(|\.readUnshared\s*\(|XMLDecoder|XStream\.fromXML|SerializationUtils\.deserialize)"#,
        languages: &["java"],
        cwe: "CWE-502",
        remediation: "Use allowlisting with ObjectInputFilter, avoid Java serialization",
        false_positive_hint: "Check if data source is trusted and filtered",
    },
    VulnRule {
        id: "JAVA-XXE-001",
        name: "XXE (Java)",
        description: "XML parser without disabled external entities",
        category: VulnCategory::XXE,
        severity: Severity::High,
        pattern: r#"(?i)(?:DocumentBuilderFactory|SAXParserFactory|XMLInputFactory|TransformerFactory|XMLReader|SchemaFactory)\.new(?:Instance|Factory)\s*\("#,
        languages: &["java"],
        cwe: "CWE-611",
        remediation: "Disable external entities: setFeature DISALLOW_DOCTYPE_DECL",
        false_positive_hint: "Check if external entities are disabled after factory creation",
    },
    VulnRule {
        id: "JAVA-PATH-001",
        name: "Path Traversal (Java)",
        description: "User input in file operations",
        category: VulnCategory::PathTraversal,
        severity: Severity::High,
        pattern: r#"(?i)new\s+(?:File|FileInputStream|FileOutputStream|FileReader|FileWriter|RandomAccessFile)\s*\(.*(?:request|param|input|getParameter|user)"#,
        languages: &["java"],
        cwe: "CWE-22",
        remediation: "Canonicalize path and verify it's within allowed directory",
        false_positive_hint: "Check if path is validated",
    },
    VulnRule {
        id: "JAVA-SSRF-001",
        name: "SSRF (Java)",
        description: "User-controlled URL in HTTP request",
        category: VulnCategory::SSRF,
        severity: Severity::High,
        pattern: r#"(?i)(?:new\s+URL|HttpURLConnection|HttpClient|RestTemplate|WebClient|OkHttpClient)\s*(?:\(|\.).*(?:request|param|input|getParameter|user)"#,
        languages: &["java"],
        cwe: "CWE-918",
        remediation: "Validate and whitelist URLs, block internal IP ranges",
        false_positive_hint: "Check URL source",
    },
    VulnRule {
        id: "JAVA-CRYPTO-001",
        name: "Weak Crypto (Java)",
        description: "Use of broken crypto algorithms",
        category: VulnCategory::WeakCrypto,
        severity: Severity::Medium,
        pattern: r#"(?i)(?:Cipher\.getInstance\s*\(\s*["\'](?:DES|RC[24]|Blowfish|DESede|ECB)|MessageDigest\.getInstance\s*\(\s*["\'](?:MD5|SHA-?1)["\']|SecretKeySpec\s*\(.*["\']DES)"#,
        languages: &["java"],
        cwe: "CWE-327",
        remediation: "Use AES-GCM for encryption, SHA-256+ for hashing",
        false_positive_hint: "MD5/SHA1 for checksums is acceptable",
    },
    VulnRule {
        id: "JAVA-LOG-001",
        name: "Log Injection / Log4Shell pattern (Java)",
        description: "User input in log statements — potential Log4Shell or log forging",
        category: VulnCategory::Injection,
        severity: Severity::High,
        pattern: r#"(?i)(?:logger|log|LOG)\s*\.(?:info|warn|error|debug|trace|fatal)\s*\(.*(?:request|getParameter|getHeader|getCookie|param|input|user)\b"#,
        languages: &["java"],
        cwe: "CWE-117",
        remediation: "Sanitize log input, use parameterized logging, patch Log4j",
        false_positive_hint: "Check if Log4j is patched (2.17+)",
    },
    VulnRule {
        id: "JAVA-LDAP-001",
        name: "LDAP Injection (Java)",
        description: "User input in LDAP search filter",
        category: VulnCategory::LDAPInjection,
        severity: Severity::High,
        pattern: r#"(?i)(?:search|DirContext\.search)\s*\(.*(?:\+|concat).*(?:request|param|input|user|getParameter)"#,
        languages: &["java"],
        cwe: "CWE-90",
        remediation: "Use parameterized LDAP queries or escape special characters",
        false_positive_hint: "Check if input is escaped",
    },
    VulnRule {
        id: "JAVA-SSTI-001",
        name: "Template Injection (Java)",
        description: "User input in template engine rendering",
        category: VulnCategory::TemplateInjection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:Velocity\.evaluate|engine\.eval|templateEngine\.process|freemarker\.template)\s*\(.*(?:request|param|input|user|getParameter)"#,
        languages: &["java"],
        cwe: "CWE-1336",
        remediation: "Never pass user input into template strings",
        false_positive_hint: "Check if user input reaches template",
    },
];

// ========================== C / C++ ==========================
pub static C_RULES: &[VulnRule] = &[
    VulnRule {
        id: "C-BOF-001",
        name: "Buffer Overflow - Unsafe Functions",
        description: "Use of inherently unsafe string functions (gets, strcpy, strcat, sprintf)",
        category: VulnCategory::BufferOverflow,
        severity: Severity::Critical,
        pattern: r#"\b(?:gets|strcpy|strcat|sprintf|vsprintf|scanf|sscanf|fscanf)\s*\("#,
        languages: &["c", "cpp", "h", "hpp", "cc", "cxx"],
        cwe: "CWE-120",
        remediation: "Use bounded alternatives: fgets, strncpy, strncat, snprintf",
        false_positive_hint: "Always a concern — replace with safe alternatives",
    },
    VulnRule {
        id: "C-BOF-002",
        name: "Buffer Overflow - Unchecked Length",
        description: "memcpy/memmove with potentially unchecked size parameter",
        category: VulnCategory::BufferOverflow,
        severity: Severity::High,
        pattern: r#"\b(?:memcpy|memmove|memset|bcopy)\s*\([^)]*(?:strlen|sizeof\s*\*|argv|argc|input|buf|data|user|param|request)"#,
        languages: &["c", "cpp", "h", "hpp", "cc", "cxx"],
        cwe: "CWE-120",
        remediation: "Validate buffer sizes before memory operations",
        false_positive_hint: "Check if size is properly bounded",
    },
    VulnRule {
        id: "C-FMT-001",
        name: "Format String Vulnerability",
        description: "User-controlled format string in printf family",
        category: VulnCategory::FormatString,
        severity: Severity::Critical,
        pattern: r#"\b(?:printf|fprintf|sprintf|snprintf|vprintf|syslog)\s*\(\s*(?:[^",]*,\s*)*(?:buf|buffer|input|data|user|str|msg|argv|arg|param|request)\s*\)"#,
        languages: &["c", "cpp", "h", "hpp", "cc", "cxx"],
        cwe: "CWE-134",
        remediation: "Always use format string: printf(\"%s\", user_input)",
        false_positive_hint: "Check if variable is used as the format string itself",
    },
    VulnRule {
        id: "C-INT-001",
        name: "Integer Overflow",
        description: "Integer arithmetic without overflow checking near allocation/size",
        category: VulnCategory::IntegerOverflow,
        severity: Severity::High,
        pattern: r#"(?:malloc|calloc|realloc|alloca)\s*\([^)]*(?:\*|\+)\s*(?:sizeof|len|size|count|num|n\b)"#,
        languages: &["c", "cpp", "h", "hpp", "cc", "cxx"],
        cwe: "CWE-190",
        remediation: "Check for overflow before arithmetic: if (a > SIZE_MAX / b)",
        false_positive_hint: "Check if overflow is validated",
    },
    VulnRule {
        id: "C-UAF-001",
        name: "Potential Use-After-Free",
        description: "Pointer potentially used after free — verify pointer is not accessed after this free()",
        category: VulnCategory::UseAfterFree,
        severity: Severity::Medium,
        pattern: r#"free\s*\(\s*(\w+)\s*\)\s*;"#,
        languages: &["c", "cpp", "h", "hpp", "cc", "cxx"],
        cwe: "CWE-416",
        remediation: "Set pointer to NULL after free: free(ptr); ptr = NULL;",
        false_positive_hint: "Only a true UAF if the pointer is read/written AFTER the free(). If free() is the last use or ptr is set to NULL immediately after, this is safe.",
    },
    VulnRule {
        id: "C-CMD-001",
        name: "Command Injection (C/C++)",
        description: "User input in system() or popen()",
        category: VulnCategory::CommandInjection,
        severity: Severity::Critical,
        pattern: r#"\b(?:system|popen|exec[lv]p?e?)\s*\([^)]*(?:argv|argc|input|buf|data|user|param|getenv|fgets)"#,
        languages: &["c", "cpp", "h", "hpp", "cc", "cxx"],
        cwe: "CWE-78",
        remediation: "Use exec* family with explicit arguments, never system() with user input",
        false_positive_hint: "Check if input is user-controlled",
    },
    VulnRule {
        id: "C-RACE-001",
        name: "TOCTOU Race Condition",
        description: "Time-of-check time-of-use race on filesystem",
        category: VulnCategory::RaceCondition,
        severity: Severity::Medium,
        pattern: r#"(?:access|stat|lstat)\s*\([^)]*\).*(?:open|fopen|unlink|rename|chmod|chown)\s*\("#,
        languages: &["c", "cpp", "h", "hpp", "cc", "cxx"],
        cwe: "CWE-367",
        remediation: "Use file descriptors instead of paths, open with O_NOFOLLOW",
        false_positive_hint: "Check if check and use are on same file",
    },
    VulnRule {
        id: "C-RAND-001",
        name: "Insecure Random (C/C++)",
        description: "Using rand()/srand() for security purposes",
        category: VulnCategory::InsecureRandom,
        severity: Severity::Medium,
        pattern: r#"\b(?:rand|srand|random|srandom)\s*\(\s*\)"#,
        languages: &["c", "cpp", "h", "hpp", "cc", "cxx"],
        cwe: "CWE-338",
        remediation: "Use /dev/urandom, getrandom(), or arc4random()",
        false_positive_hint: "Acceptable for non-security uses",
    },
];

// ========================== GO ==========================
pub static GO_RULES: &[VulnRule] = &[
    VulnRule {
        id: "GO-INJ-001",
        name: "SQL Injection (Go)",
        description: "String formatting in SQL query",
        category: VulnCategory::Injection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:db\.(?:Query|Exec|QueryRow|Prepare)|\.(?:Raw|Where|Order|Group|Having|Select))\s*\(\s*(?:fmt\.Sprintf|.*\+)"#,
        languages: &["go"],
        cwe: "CWE-89",
        remediation: "Use parameterized queries with ? or $1 placeholders",
        false_positive_hint: "Check if using parameterized query",
    },
    VulnRule {
        id: "GO-CMD-001",
        name: "Command Injection (Go)",
        description: "User input in exec.Command with shell",
        category: VulnCategory::CommandInjection,
        severity: Severity::Critical,
        pattern: r#"(?i)exec\.Command\s*\(\s*["\'](?:sh|bash|cmd|/bin/sh|/bin/bash)["\'].*(?:request|param|input|user|r\.(?:URL|Form|Body)|fmt\.Sprintf)"#,
        languages: &["go"],
        cwe: "CWE-78",
        remediation: "Use exec.Command with explicit arguments, never shell -c with user input",
        false_positive_hint: "Check if input is user-controlled",
    },
    VulnRule {
        id: "GO-SSRF-001",
        name: "SSRF (Go)",
        description: "User-controlled URL in HTTP request",
        category: VulnCategory::SSRF,
        severity: Severity::High,
        pattern: r#"(?i)(?:http\.(?:Get|Post|Head|NewRequest)|httpClient\.Do)\s*\(.*(?:r\.(?:URL|Form|Body)|request|param|input|user|fmt\.Sprintf)"#,
        languages: &["go"],
        cwe: "CWE-918",
        remediation: "Validate URLs, block internal IPs",
        false_positive_hint: "Check URL source",
    },
    VulnRule {
        id: "GO-PATH-001",
        name: "Path Traversal (Go)",
        description: "User input in file path",
        category: VulnCategory::PathTraversal,
        severity: Severity::High,
        pattern: r#"(?i)(?:os\.(?:Open|Create|ReadFile|WriteFile)|ioutil\.(?:ReadFile|WriteFile)|filepath\.(?:Join|Clean))\s*\(.*(?:r\.(?:URL|Form|Body)|request|param|input|user)"#,
        languages: &["go"],
        cwe: "CWE-22",
        remediation: "Use filepath.Clean and verify path prefix",
        false_positive_hint: "Check if path is validated",
    },
    VulnRule {
        id: "GO-TMPL-001",
        name: "Template Injection (Go)",
        description: "User input in template parsing",
        category: VulnCategory::TemplateInjection,
        severity: Severity::High,
        pattern: r#"(?i)template\.(?:New|Must)\s*\(.*(?:r\.|request|param|input|user)"#,
        languages: &["go"],
        cwe: "CWE-1336",
        remediation: "Never parse user input as template",
        false_positive_hint: "Check if user input reaches template parser",
    },
    VulnRule {
        id: "GO-CRYPTO-001",
        name: "Weak Crypto (Go)",
        description: "Use of weak crypto algorithms",
        category: VulnCategory::WeakCrypto,
        severity: Severity::Medium,
        pattern: r#"(?i)(?:md5\.(?:New|Sum)|sha1\.(?:New|Sum)|des\.|rc4\.)"#,
        languages: &["go"],
        cwe: "CWE-327",
        remediation: "Use sha256, aes-gcm",
        false_positive_hint: "Checksums with MD5 are acceptable",
    },
];

// ========================== PHP ==========================
pub static PHP_RULES: &[VulnRule] = &[
    VulnRule {
        id: "PHP-INJ-001",
        name: "SQL Injection (PHP)",
        description: "Variable interpolation or concatenation in SQL query",
        category: VulnCategory::Injection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:mysql_query|mysqli_query|->query|pg_query|->execute)\s*\(\s*(?:["'].*\.\s*\$|["'].*\$\{|["'].*\$_(?:GET|POST|REQUEST|COOKIE))"#,
        languages: &["php"],
        cwe: "CWE-89",
        remediation: "Use PDO prepared statements with bound parameters",
        false_positive_hint: "Check if using prepared statements",
    },
    VulnRule {
        id: "PHP-INJ-002",
        name: "Command Injection (PHP)",
        description: "User input in shell execution",
        category: VulnCategory::CommandInjection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:exec|system|passthru|shell_exec|popen|proc_open|pcntl_exec|`)\s*\(\s*(?:.*\$_(?:GET|POST|REQUEST|COOKIE|SERVER)|.*\$(?:input|user|param|data|cmd|command))"#,
        languages: &["php"],
        cwe: "CWE-78",
        remediation: "Use escapeshellarg() and escapeshellcmd(), prefer exec with array args",
        false_positive_hint: "Check if input is escaped",
    },
    VulnRule {
        id: "PHP-XSS-001",
        name: "XSS (PHP)",
        description: "Direct output of user input without encoding",
        category: VulnCategory::XSS,
        severity: Severity::High,
        pattern: r#"(?i)(?:echo|print|print_r|die|exit)\s+(?:.*\$_(?:GET|POST|REQUEST|COOKIE|SERVER)|.*\$(?:input|user|param|data))"#,
        languages: &["php"],
        cwe: "CWE-79",
        remediation: "Use htmlspecialchars() with ENT_QUOTES and UTF-8",
        false_positive_hint: "Check if output is encoded",
    },
    VulnRule {
        id: "PHP-DESER-001",
        name: "Insecure Deserialization (PHP)",
        description: "unserialize() on user-controlled data",
        category: VulnCategory::InsecureDeserialization,
        severity: Severity::Critical,
        pattern: r#"(?i)unserialize\s*\(\s*(?:\$_(?:GET|POST|REQUEST|COOKIE)|.*(?:input|user|param|data|body|request))"#,
        languages: &["php"],
        cwe: "CWE-502",
        remediation: "Use json_decode instead, or use allowed_classes option",
        false_positive_hint: "Check data source",
    },
    VulnRule {
        id: "PHP-FILE-001",
        name: "File Inclusion (PHP)",
        description: "User input in include/require — LFI/RFI",
        category: VulnCategory::PathTraversal,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:include|require|include_once|require_once)\s*\(\s*(?:\$_(?:GET|POST|REQUEST|COOKIE)|.*(?:input|user|param|data|file|page|path))"#,
        languages: &["php"],
        cwe: "CWE-98",
        remediation: "Whitelist allowed files, never use user input in include paths",
        false_positive_hint: "Check if path is whitelisted",
    },
    VulnRule {
        id: "PHP-SSRF-001",
        name: "SSRF (PHP)",
        description: "User input in URL fetch",
        category: VulnCategory::SSRF,
        severity: Severity::High,
        pattern: r#"(?i)(?:file_get_contents|curl_setopt.*CURLOPT_URL|fopen)\s*\(\s*(?:\$_(?:GET|POST|REQUEST)|.*(?:input|user|param|url))"#,
        languages: &["php"],
        cwe: "CWE-918",
        remediation: "Validate and whitelist URLs",
        false_positive_hint: "Check URL source",
    },
    VulnRule {
        id: "PHP-EVAL-001",
        name: "Code Injection (PHP)",
        description: "eval/assert with user input",
        category: VulnCategory::Injection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:eval|assert|preg_replace\s*\(.*\/e)\s*\(\s*(?:\$_(?:GET|POST|REQUEST|COOKIE)|.*(?:input|user|param|data))"#,
        languages: &["php"],
        cwe: "CWE-94",
        remediation: "Never use eval with user input",
        false_positive_hint: "Check if argument is user-controlled",
    },
];

// ========================== RUBY ==========================
pub static RUBY_RULES: &[VulnRule] = &[
    VulnRule {
        id: "RB-INJ-001",
        name: "SQL Injection (Ruby)",
        description: "String interpolation in ActiveRecord query",
        category: VulnCategory::Injection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:\.where|\.find_by_sql|\.order|\.group|\.having|\.pluck|\.select|\.joins)\s*\(\s*["'].*#\{"#,
        languages: &["rb"],
        cwe: "CWE-89",
        remediation: "Use parameterized queries: where('name = ?', name)",
        false_positive_hint: "Check if using parameterized form",
    },
    VulnRule {
        id: "RB-CMD-001",
        name: "Command Injection (Ruby)",
        description: "User input in system/exec/backtick",
        category: VulnCategory::CommandInjection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:system|exec|`|%x\[|IO\.popen|Open3\.\w+|Kernel\.system)\s*(?:\(?\s*["'].*#\{|.*params|.*request)"#,
        languages: &["rb"],
        cwe: "CWE-78",
        remediation: "Use array form of system(): system('cmd', arg1, arg2)",
        false_positive_hint: "Check if input is user-controlled",
    },
    VulnRule {
        id: "RB-DESER-001",
        name: "Insecure Deserialization (Ruby)",
        description: "Marshal.load or YAML.load on untrusted data",
        category: VulnCategory::InsecureDeserialization,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:Marshal\.load|YAML\.load|Oj\.load)\s*\(.*(?:params|request|input|user|data|body)"#,
        languages: &["rb"],
        cwe: "CWE-502",
        remediation: "Use YAML.safe_load, avoid Marshal on untrusted data",
        false_positive_hint: "Check data source",
    },
    VulnRule {
        id: "RB-XSS-001",
        name: "XSS (Ruby on Rails)",
        description: "raw/html_safe with user input",
        category: VulnCategory::XSS,
        severity: Severity::High,
        pattern: r#"(?i)(?:\.html_safe|raw\s*\(|<%==)\s*.*(?:params|request|input|user)"#,
        languages: &["rb", "erb"],
        cwe: "CWE-79",
        remediation: "Use ERB auto-escaping, avoid html_safe on user input",
        false_positive_hint: "Check if content is from trusted source",
    },
    VulnRule {
        id: "RB-MASS-001",
        name: "Mass Assignment (Ruby on Rails)",
        description: "permit! or unfiltered params in mass assignment",
        category: VulnCategory::MassAssignment,
        severity: Severity::High,
        pattern: r#"(?i)(?:\.permit!|params\.(?:to_unsafe_h|to_h)|attr_accessible\s*:all|without_protection)"#,
        languages: &["rb"],
        cwe: "CWE-915",
        remediation: "Use strong parameters with explicit permit list",
        false_positive_hint: "Check if used intentionally in admin context",
    },
];

// ========================== RUST ==========================
pub static RUST_RULES: &[VulnRule] = &[
    VulnRule {
        id: "RS-UNSAFE-001",
        name: "Unsafe Block Usage",
        description: "Unsafe code block — potential memory safety issues",
        category: VulnCategory::BufferOverflow,
        severity: Severity::Medium,
        pattern: r#"\bunsafe\s*\{"#,
        languages: &["rs"],
        cwe: "CWE-676",
        remediation: "Minimize unsafe blocks, document safety invariants",
        false_positive_hint: "Unsafe is sometimes necessary — review the block",
    },
    VulnRule {
        id: "RS-CMD-001",
        name: "Command Injection (Rust)",
        description: "User input in shell command",
        category: VulnCategory::CommandInjection,
        severity: Severity::Critical,
        pattern: r#"(?i)Command::new\s*\(\s*(?:["'](?:sh|bash|cmd)["\']|.*(?:input|user|arg|param|request))"#,
        languages: &["rs"],
        cwe: "CWE-78",
        remediation: "Use Command::new with .arg() for each argument, never shell -c",
        false_positive_hint: "Check if input is user-controlled",
    },
    VulnRule {
        id: "RS-SQL-001",
        name: "SQL Injection (Rust)",
        description: "String formatting in SQL query",
        category: VulnCategory::Injection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:execute|query|query_one|query_opt|query_row|batch_execute)\s*\(\s*&?format!"#,
        languages: &["rs"],
        cwe: "CWE-89",
        remediation: "Use parameterized queries with $1, $2 placeholders",
        false_positive_hint: "Check if using query parameters",
    },
    VulnRule {
        id: "RS-PATH-001",
        name: "Path Traversal (Rust)",
        description: "User input in file path operations",
        category: VulnCategory::PathTraversal,
        severity: Severity::High,
        pattern: r#"(?i)(?:File::(?:open|create)|fs::(?:read|write|read_to_string|remove))\s*\(\s*(?:&?format!|.*(?:input|user|param|request|arg))"#,
        languages: &["rs"],
        cwe: "CWE-22",
        remediation: "Canonicalize path and check it starts with allowed prefix",
        false_positive_hint: "Check if path is validated",
    },
];

// ========================== CSHARP ==========================
pub static CSHARP_RULES: &[VulnRule] = &[
    VulnRule {
        id: "CS-INJ-001",
        name: "SQL Injection (C#)",
        description: "String concatenation in SQL command",
        category: VulnCategory::Injection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:SqlCommand|OleDbCommand|OracleCommand|new\s+.*Command)\s*\(\s*(?:["'].*\+|\$"|.*string\.Format|.*String\.Concat)"#,
        languages: &["cs"],
        cwe: "CWE-89",
        remediation: "Use SqlParameter with parameterized queries",
        false_positive_hint: "Check if parameters are bound",
    },
    VulnRule {
        id: "CS-DESER-001",
        name: "Insecure Deserialization (C#)",
        description: "BinaryFormatter/TypeNameHandling.All — RCE gadgets",
        category: VulnCategory::InsecureDeserialization,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:BinaryFormatter|SoapFormatter|ObjectStateFormatter|LosFormatter|NetDataContractSerializer|TypeNameHandling\s*\.?\s*(?:All|Auto|Objects|Arrays))"#,
        languages: &["cs"],
        cwe: "CWE-502",
        remediation: "Use System.Text.Json, avoid BinaryFormatter",
        false_positive_hint: "Check if data source is trusted",
    },
    VulnRule {
        id: "CS-XSS-001",
        name: "XSS (C# / ASP.NET)",
        description: "Unencoded user output",
        category: VulnCategory::XSS,
        severity: Severity::High,
        pattern: r#"(?i)(?:@Html\.Raw|Response\.Write|<%=)\s*\(?\s*(?:Request|Model|ViewBag|ViewData|TempData|input|user|param)"#,
        languages: &["cs", "cshtml"],
        cwe: "CWE-79",
        remediation: "Use @Html.Encode or Razor auto-encoding",
        false_positive_hint: "Check if output is encoded",
    },
    VulnRule {
        id: "CS-CMD-001",
        name: "Command Injection (C#)",
        description: "User input in Process.Start",
        category: VulnCategory::CommandInjection,
        severity: Severity::Critical,
        pattern: r#"(?i)Process\.Start\s*\(.*(?:Request|input|user|param|args|query)"#,
        languages: &["cs"],
        cwe: "CWE-78",
        remediation: "Validate and sanitize arguments, avoid shell execution",
        false_positive_hint: "Check if input is user-controlled",
    },
    VulnRule {
        id: "CS-XXE-001",
        name: "XXE (C#)",
        description: "XML parsing without disabling external entities",
        category: VulnCategory::XXE,
        severity: Severity::High,
        pattern: r#"(?i)(?:XmlDocument|XmlTextReader|XmlReader\.Create|XDocument\.Load)\s*(?:\(\)|\.)"#,
        languages: &["cs"],
        cwe: "CWE-611",
        remediation: "Set DtdProcessing = DtdProcessing.Prohibit",
        false_positive_hint: "Check if DTD processing is disabled",
    },
];

// ========================== KOTLIN / SWIFT / SCALA ==========================
pub static MOBILE_RULES: &[VulnRule] = &[
    VulnRule {
        id: "KT-INJ-001",
        name: "SQL Injection (Kotlin/Android)",
        description: "String template in rawQuery",
        category: VulnCategory::Injection,
        severity: Severity::Critical,
        pattern: r#"(?i)(?:rawQuery|execSQL|compileStatement)\s*\(\s*(?:["'].*\$|.*\+|.*string\.format)"#,
        languages: &["kt", "kts"],
        cwe: "CWE-89",
        remediation: "Use ? placeholders with selectionArgs array",
        false_positive_hint: "Check if using parameterized query",
    },
    VulnRule {
        id: "KT-LOG-001",
        name: "Sensitive Data in Logs (Kotlin/Android)",
        description: "Logging potentially sensitive data",
        category: VulnCategory::InfoDisclosure,
        severity: Severity::Medium,
        pattern: r#"(?i)(?:Log\.(?:d|i|w|e|v)|println|Timber\.\w+)\s*\(.*(?:password|token|secret|key|credential|ssn|credit.?card|api.?key)"#,
        languages: &["kt", "kts", "swift"],
        cwe: "CWE-532",
        remediation: "Remove sensitive data from log statements",
        false_positive_hint: "Verify if logs contain real sensitive data",
    },
    VulnRule {
        id: "SWIFT-KEYCHAIN-001",
        name: "Insecure Data Storage (Swift/iOS)",
        description: "Storing sensitive data in UserDefaults instead of Keychain",
        category: VulnCategory::InsecureFileOps,
        severity: Severity::Medium,
        pattern: r#"(?i)UserDefaults\.standard\.set\s*\(.*(?:password|token|secret|key|credential|session)"#,
        languages: &["swift"],
        cwe: "CWE-922",
        remediation: "Use Keychain for sensitive data storage",
        false_positive_hint: "Check if data is truly sensitive",
    },
];

// ========================== SOLIDITY / SMART CONTRACTS ==========================
pub static SOLIDITY_RULES: &[VulnRule] = &[
    VulnRule {
        id: "SOL-REENT-001",
        name: "Reentrancy Vulnerability",
        description: "External call before state update — classic reentrancy attack vector",
        category: VulnCategory::RaceCondition,
        severity: Severity::Critical,
        pattern: r#"\.call\{.*value"#,
        languages: &["sol"],
        cwe: "CWE-841",
        remediation: "Use checks-effects-interactions pattern or ReentrancyGuard. Update state variables before external calls.",
        false_positive_hint: "Check if nonReentrant modifier or state update before call",
    },
    VulnRule {
        id: "SOL-ARITH-001",
        name: "Unchecked Arithmetic (pre-0.8)",
        description: "Arithmetic operation without SafeMath in Solidity < 0.8",
        category: VulnCategory::IntegerOverflow,
        severity: Severity::High,
        pattern: r#"(?:unchecked\s*\{|pragma\s+solidity\s+(?:0\.[4-7]|\^0\.[4-7]))"#,
        languages: &["sol"],
        cwe: "CWE-190",
        remediation: "Use Solidity >= 0.8 with built-in overflow checks, or use OpenZeppelin SafeMath",
        false_positive_hint: "Check if using SafeMath or Solidity >= 0.8",
    },
    VulnRule {
        id: "SOL-AUTH-001",
        name: "tx.origin Authentication",
        description: "Using tx.origin for authorization is vulnerable to phishing attacks",
        category: VulnCategory::BrokenAuth,
        severity: Severity::High,
        pattern: r#"tx\.origin"#,
        languages: &["sol"],
        cwe: "CWE-284",
        remediation: "Use msg.sender instead of tx.origin for authentication",
        false_positive_hint: "Check if tx.origin is used for auth vs logging",
    },
    VulnRule {
        id: "SOL-DELEG-001",
        name: "Delegatecall to User-Controlled Address",
        description: "delegatecall to a variable address allows arbitrary code execution in caller context",
        category: VulnCategory::Injection,
        severity: Severity::Critical,
        pattern: r#"\.delegatecall\("#,
        languages: &["sol"],
        cwe: "CWE-94",
        remediation: "Only delegatecall to trusted, hardcoded contract addresses",
        false_positive_hint: "Check if delegatecall target is a constant",
    },
    VulnRule {
        id: "SOL-DESTR-001",
        name: "Unprotected Selfdestruct",
        description: "selfdestruct without access control allows anyone to destroy the contract",
        category: VulnCategory::PrivilegeEscalation,
        severity: Severity::Critical,
        pattern: r#"selfdestruct\s*\("#,
        languages: &["sol"],
        cwe: "CWE-284",
        remediation: "Add onlyOwner or similar access control to selfdestruct",
        false_positive_hint: "Check if function has access control modifier",
    },
    VulnRule {
        id: "SOL-FRONT-001",
        name: "Front-Running Vulnerable Pattern",
        description: "State-dependent operation without commit-reveal or time-lock protection",
        category: VulnCategory::RaceCondition,
        severity: Severity::Medium,
        pattern: r#"block\.(?:timestamp|number|difficulty|coinbase)"#,
        languages: &["sol"],
        cwe: "CWE-362",
        remediation: "Use commit-reveal scheme or block hash for randomness; avoid block.timestamp for critical logic",
        false_positive_hint: "Check if used for non-critical timing",
    },
];

pub fn all_rules() -> Vec<&'static VulnRule> {
    let mut rules: Vec<&'static VulnRule> = Vec::new();
    for r in PYTHON_RULES { rules.push(r); }
    for r in JS_RULES { rules.push(r); }
    for r in JAVA_RULES { rules.push(r); }
    for r in C_RULES { rules.push(r); }
    for r in GO_RULES { rules.push(r); }
    for r in PHP_RULES { rules.push(r); }
    for r in RUBY_RULES { rules.push(r); }
    for r in RUST_RULES { rules.push(r); }
    for r in CSHARP_RULES { rules.push(r); }
    for r in MOBILE_RULES { rules.push(r); }
    for r in SOLIDITY_RULES { rules.push(r); }
    // Extended rules (Semgrep-inspired patterns)
    rules.extend(crate::patterns::language_extended::all_extended_rules());
    rules
}
