use crate::patterns::vuln_rules::*;

// ============================================================
// EXTENDED VULNERABILITY RULES — 150+ additional patterns
// Inspired by Semgrep Registry, CodeQL queries, OWASP Top 10
// ============================================================

// ========================== PYTHON EXTENDED ==========================
pub static PYTHON_EXT_RULES: &[VulnRule] = &[
    VulnRule {
        id: "PY-CSRF-001", name: "Missing CSRF Protection (Django)",
        description: "View with @csrf_exempt — CSRF attacks possible",
        category: VulnCategory::CSRF, severity: Severity::High,
        pattern: r#"@csrf_exempt"#,
        languages: &["py"], cwe: "CWE-352",
        remediation: "Remove @csrf_exempt, use Django's built-in CSRF middleware",
        false_positive_hint: "May be intentional for API endpoints using token auth",
    },
    VulnRule {
        id: "PY-AUTH-001", name: "Hardcoded JWT Secret (Python)",
        description: "JWT signing with hardcoded secret key",
        category: VulnCategory::HardcodedSecret, severity: Severity::Critical,
        pattern: r#"(?i)jwt\.encode\s*\(.*(?:secret|key)\s*=\s*["'][^"']{4,}["']"#,
        languages: &["py"], cwe: "CWE-798",
        remediation: "Use environment variable for JWT secret: os.environ['JWT_SECRET']",
        false_positive_hint: "Check if secret is from env var or config",
    },
    VulnRule {
        id: "PY-AUTH-002", name: "Flask Debug Mode",
        description: "Flask running with debug=True — RCE via debugger PIN",
        category: VulnCategory::Misconfiguration, severity: Severity::High,
        pattern: r#"(?i)(?:app\.run\s*\(.*debug\s*=\s*True|app\.debug\s*=\s*True|DEBUG\s*=\s*True)"#,
        languages: &["py"], cwe: "CWE-489",
        remediation: "Disable debug mode in production: DEBUG = False",
        false_positive_hint: "Check if this is development-only config",
    },
    VulnRule {
        id: "PY-SEC-001", name: "Insecure Hash for Password (Python)",
        description: "Using MD5/SHA1 for password hashing instead of bcrypt/argon2",
        category: VulnCategory::WeakCrypto, severity: Severity::High,
        pattern: r#"(?i)hashlib\.(?:md5|sha1)\s*\(.*(?:password|passwd|pwd)"#,
        languages: &["py"], cwe: "CWE-916",
        remediation: "Use bcrypt, argon2, or scrypt for password hashing",
        false_positive_hint: "MD5/SHA1 for non-password checksums is acceptable",
    },
    VulnRule {
        id: "PY-SEC-002", name: "Binding to All Interfaces (Python)",
        description: "Server bound to 0.0.0.0 — accessible from all networks",
        category: VulnCategory::Misconfiguration, severity: Severity::Low,
        pattern: r#"(?i)\.run\s*\(.*host\s*=\s*["']0\.0\.0\.0["']"#,
        languages: &["py"], cwe: "CWE-668",
        remediation: "Bind to 127.0.0.1 for local access only in development",
        false_positive_hint: "May be intentional for containerized deployments",
    },
    VulnRule {
        id: "PY-SEC-003", name: "Python Temporary File Race Condition",
        description: "Using mktemp — vulnerable to race conditions",
        category: VulnCategory::RaceCondition, severity: Severity::Medium,
        pattern: r#"(?i)(?:tempfile\.mktemp|os\.tempnam|os\.tmpnam)\s*\("#,
        languages: &["py"], cwe: "CWE-377",
        remediation: "Use tempfile.mkstemp() or tempfile.NamedTemporaryFile()",
        false_positive_hint: "Check if atomicity is guaranteed by other means",
    },
    VulnRule {
        id: "PY-SEC-004", name: "Python Assert in Production",
        description: "Using assert for security checks — disabled with -O flag",
        category: VulnCategory::Misconfiguration, severity: Severity::Medium,
        pattern: r#"assert\s+.*(?:is_authenticated|is_admin|has_permission|is_authorized|is_valid|verify)"#,
        languages: &["py"], cwe: "CWE-617",
        remediation: "Use if/raise instead of assert for security checks",
        false_positive_hint: "Assert in tests is fine",
    },
    VulnRule {
        id: "PY-SSRF-002", name: "DNS Rebinding via urllib (Python)",
        description: "urllib/requests following redirects to internal IPs",
        category: VulnCategory::SSRF, severity: Severity::High,
        pattern: r#"(?i)(?:urllib\.request\.urlopen|requests\.\w+)\s*\(.*(?:allow_redirects\s*=\s*True|follow_redirects)"#,
        languages: &["py"], cwe: "CWE-918",
        remediation: "Validate redirected URLs, block internal IP ranges after redirect",
        false_positive_hint: "Check if URL is user-controlled",
    },
    VulnRule {
        id: "PY-NOSQL-001", name: "NoSQL Injection (Python/MongoDB)",
        description: "User input in MongoDB query without sanitization",
        category: VulnCategory::Injection, severity: Severity::High,
        pattern: r#"(?i)(?:collection|db)\.\w+\.\s*(?:find|find_one|update|delete|aggregate)\s*\(.*(?:request|param|args|form|json)"#,
        languages: &["py"], cwe: "CWE-943",
        remediation: "Validate and sanitize input, use projection operators",
        false_positive_hint: "Check if input is validated",
    },
    VulnRule {
        id: "PY-LOG-001", name: "Sensitive Data in Logs (Python)",
        description: "Logging potentially sensitive data (passwords, tokens, keys)",
        category: VulnCategory::InfoDisclosure, severity: Severity::Medium,
        pattern: r#"(?i)(?:logging|logger|log)\.\w+\(.*(?:password|token|secret|key|credential|session_id|credit_card|ssn)"#,
        languages: &["py"], cwe: "CWE-532",
        remediation: "Filter sensitive data before logging, use data masking",
        false_positive_hint: "Check if sensitive fields are redacted",
    },
    VulnRule {
        id: "PY-CORS-001", name: "Flask CORS Allow All",
        description: "Flask CORS configured to allow all origins",
        category: VulnCategory::Misconfiguration, severity: Severity::Medium,
        pattern: r#"(?i)CORS\s*\(\s*app\s*(?:,\s*resources\s*=\s*r?[\"']\*)?(?:\s*\)|\s*,)"#,
        languages: &["py"], cwe: "CWE-942",
        remediation: "Restrict CORS to specific trusted origins",
        false_positive_hint: "Check if origins are properly restricted",
    },
];

// ========================== JAVASCRIPT/TS EXTENDED ==========================
pub static JS_EXT_RULES: &[VulnRule] = &[
    VulnRule {
        id: "JS-PP-001", name: "Prototype Pollution via merge",
        description: "Deep merge of user-controlled object enables prototype pollution",
        category: VulnCategory::PrototypePollution, severity: Severity::High,
        pattern: r#"(?i)(?:lodash\.merge|_\.merge|deepMerge|Object\.assign|defaultsDeep|extend)\s*\(.*(?:req\.|request\.|body|query|param)"#,
        languages: &["js", "ts"], cwe: "CWE-1321",
        remediation: "Sanitize input: filter __proto__, constructor, and prototype keys",
        false_positive_hint: "Check if input is validated",
    },
    VulnRule {
        id: "JS-PP-002", name: "Prototype Pollution via bracket notation",
        description: "Dynamic property assignment using user input — prototype pollution vector",
        category: VulnCategory::PrototypePollution, severity: Severity::High,
        pattern: r#"(?i)\w+\[\s*(?:req\.|request\.|body|query|param|key)\w*\s*\]\s*="#,
        languages: &["js", "ts"], cwe: "CWE-1321",
        remediation: "Use Map instead of objects, or validate property names",
        false_positive_hint: "Check if key is from user input",
    },
    VulnRule {
        id: "JS-AUTH-001", name: "JWT Weak Secret (Node.js)",
        description: "JWT signed with weak or hardcoded secret",
        category: VulnCategory::HardcodedSecret, severity: Severity::Critical,
        pattern: r#"(?i)jwt\.sign\s*\(.*(?:secret|key)\s*[:=]\s*["'][^"']{1,20}["']"#,
        languages: &["js", "ts"], cwe: "CWE-798",
        remediation: "Use strong secrets (256+ bit) from environment variables",
        false_positive_hint: "Check if secret is from env var",
    },
    VulnRule {
        id: "JS-AUTH-002", name: "JWT None Algorithm (Node.js)",
        description: "JWT verification allowing 'none' algorithm",
        category: VulnCategory::BrokenAuth, severity: Severity::Critical,
        pattern: r#"(?i)jwt\.verify\s*\(.*(?:algorithms\s*:\s*\[.*["']none["']|options.*algorithms.*none)"#,
        languages: &["js", "ts"], cwe: "CWE-345",
        remediation: "Always specify allowed algorithms: algorithms: ['HS256']",
        false_positive_hint: "Check algorithm configuration",
    },
    VulnRule {
        id: "JS-SEC-001", name: "Express Trust Proxy Misconfiguration",
        description: "Express trust proxy set to true — IP spoofing risk",
        category: VulnCategory::Misconfiguration, severity: Severity::Medium,
        pattern: r#"(?i)app\.set\s*\(\s*["']trust\s+proxy["']\s*,\s*true\s*\)"#,
        languages: &["js", "ts"], cwe: "CWE-348",
        remediation: "Set trust proxy to specific proxy count or IP addresses",
        false_positive_hint: "May be valid behind a known reverse proxy",
    },
    VulnRule {
        id: "JS-SEC-002", name: "Node.js TLS Reject Unauthorized Disabled",
        description: "TLS certificate verification globally disabled",
        category: VulnCategory::InsecureTLS, severity: Severity::High,
        pattern: r#"NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*["']?0"#,
        languages: &["js", "ts"], cwe: "CWE-295",
        remediation: "Never disable TLS verification globally. Use specific CA certs instead",
        false_positive_hint: "Should only be used in test environments",
    },
    VulnRule {
        id: "JS-SEC-003", name: "Helmet Missing (Express)",
        description: "Express app without helmet security headers",
        category: VulnCategory::Misconfiguration, severity: Severity::Medium,
        pattern: r#"(?i)express\s*\(\s*\)"#,
        languages: &["js", "ts"], cwe: "CWE-693",
        remediation: "Add helmet middleware: app.use(helmet())",
        false_positive_hint: "Check if security headers are set manually",
    },
    VulnRule {
        id: "JS-SEC-004", name: "Mongoose Debug Mode",
        description: "Mongoose debug mode exposes queries in production",
        category: VulnCategory::InfoDisclosure, severity: Severity::Low,
        pattern: r#"mongoose\.set\s*\(\s*["']debug["']\s*,\s*true"#,
        languages: &["js", "ts"], cwe: "CWE-200",
        remediation: "Disable debug mode in production",
        false_positive_hint: "Check if environment-conditional",
    },
    VulnRule {
        id: "JS-REDIR-001", name: "Open Redirect (Express)",
        description: "Redirect using user-controlled URL",
        category: VulnCategory::OpenRedirect, severity: Severity::Medium,
        pattern: r#"(?i)res\.redirect\s*\(\s*(?:req\.(?:query|params|body)\.|request\.\w+)"#,
        languages: &["js", "ts"], cwe: "CWE-601",
        remediation: "Validate redirect URL against allowlist of paths",
        false_positive_hint: "Check if URL is validated",
    },
    VulnRule {
        id: "JS-CORS-001", name: "CORS Wildcard Origin (Node.js)",
        description: "CORS configured with wildcard origin",
        category: VulnCategory::Misconfiguration, severity: Severity::Medium,
        pattern: r#"(?i)(?:Access-Control-Allow-Origin.*\*|cors\(\s*\{?\s*origin\s*:\s*(?:true|["']\*["']))"#,
        languages: &["js", "ts"], cwe: "CWE-942",
        remediation: "Specify allowed origins explicitly",
        false_positive_hint: "May be valid for public APIs",
    },
    VulnRule {
        id: "JS-FILE-001", name: "Path Traversal in File Serving (Node.js)",
        description: "Serving files based on user input without path validation",
        category: VulnCategory::PathTraversal, severity: Severity::High,
        pattern: r#"(?i)(?:sendFile|res\.download|createReadStream)\s*\(.*(?:req\.|request\.|params|query)"#,
        languages: &["js", "ts"], cwe: "CWE-22",
        remediation: "Use path.resolve() and verify path is within allowed directory",
        false_positive_hint: "Check if path is validated",
    },
    VulnRule {
        id: "JS-SSRF-001", name: "SSRF via fetch/axios (Node.js)",
        description: "HTTP request with user-controlled URL",
        category: VulnCategory::SSRF, severity: Severity::High,
        pattern: r#"(?i)(?:fetch|axios\.\w+|got\(|node-fetch)\s*\(\s*(?:req\.|request\.|.*\+|`\$\{)"#,
        languages: &["js", "ts"], cwe: "CWE-918",
        remediation: "Validate and whitelist allowed URLs/domains",
        false_positive_hint: "Check if URL is user-controlled",
    },
    VulnRule {
        id: "JS-LOG-001", name: "Sensitive Data in Console.log",
        description: "Logging potentially sensitive information",
        category: VulnCategory::InfoDisclosure, severity: Severity::Medium,
        pattern: r#"(?i)console\.log\s*\(.*(?:password|token|secret|key|credential|session|apiKey)"#,
        languages: &["js", "ts"], cwe: "CWE-532",
        remediation: "Remove console.log of sensitive data, use structured logging",
        false_positive_hint: "Check if data is redacted before logging",
    },
    VulnRule {
        id: "JS-REGEX-001", name: "ReDoS — User Input in Regex (Node.js)",
        description: "User-controlled input used to construct regex — ReDoS vector",
        category: VulnCategory::RegexDoS, severity: Severity::Medium,
        pattern: r#"(?i)new\s+RegExp\s*\(\s*(?:req\.|request\.|body|query|params|user)"#,
        languages: &["js", "ts"], cwe: "CWE-1333",
        remediation: "Use RE2 library for user-supplied patterns",
        false_positive_hint: "Check if input is validated against ReDoS patterns",
    },
    VulnRule {
        id: "JS-DESER-002", name: "Unsafe JSON Parsing with reviver",
        description: "JSON.parse with Function constructor in reviver — code injection",
        category: VulnCategory::InsecureDeserialization, severity: Severity::High,
        pattern: r#"(?i)JSON\.parse\s*\(.*function\s*\(.*(?:eval|Function|new\s+Function)"#,
        languages: &["js", "ts"], cwe: "CWE-502",
        remediation: "Never use eval/Function in JSON.parse reviver",
        false_positive_hint: "Check reviver function implementation",
    },
];

// ========================== JAVA EXTENDED ==========================
pub static JAVA_EXT_RULES: &[VulnRule] = &[
    VulnRule {
        id: "JAVA-AUTH-001", name: "Spring Security Disabled",
        description: "Spring Security CSRF protection or auth disabled",
        category: VulnCategory::BrokenAuth, severity: Severity::High,
        pattern: r#"(?i)(?:\.csrf\(\)\.disable\(\)|\.authorizeRequests\(\)\.anyRequest\(\)\.permitAll\(\)|@(?:PermitAll|Anonymous))"#,
        languages: &["java", "kt"], cwe: "CWE-306",
        remediation: "Enable CSRF protection and configure proper authorization",
        false_positive_hint: "CSRF disable may be valid for stateless REST APIs",
    },
    VulnRule {
        id: "JAVA-CRYPTO-001", name: "Java Insecure TLS Version",
        description: "Using outdated TLS version (SSLv3, TLSv1.0, TLSv1.1)",
        category: VulnCategory::InsecureTLS, severity: Severity::High,
        pattern: r#"(?i)(?:SSLContext\.getInstance\s*\(\s*["'](?:SSL|SSLv3|TLS|TLSv1|TLSv1\.1)["']|setEnabledProtocols.*(?:SSLv3|TLSv1\.0|TLSv1\.1))"#,
        languages: &["java"], cwe: "CWE-326",
        remediation: "Use TLSv1.2 or TLSv1.3: SSLContext.getInstance(\"TLSv1.3\")",
        false_positive_hint: "Check if this is for compatibility with legacy systems",
    },
    VulnRule {
        id: "JAVA-CRYPTO-002", name: "Java ECB Mode Cipher",
        description: "AES/DES in ECB mode — no semantic security",
        category: VulnCategory::WeakCrypto, severity: Severity::High,
        pattern: r#"(?i)Cipher\.getInstance\s*\(\s*["'](?:AES|DES|DESede)(?:/ECB)?["']\s*\)"#,
        languages: &["java"], cwe: "CWE-327",
        remediation: "Use AES/GCM/NoPadding or AES/CBC/PKCS5Padding with HMAC",
        false_positive_hint: "Check if cipher mode is explicitly set",
    },
    VulnRule {
        id: "JAVA-SEC-001", name: "Java Reflection with User Input",
        description: "Class loading or reflection using user-controlled input",
        category: VulnCategory::Injection, severity: Severity::Critical,
        pattern: r#"(?i)(?:Class\.forName|\.loadClass|\.getMethod|\.newInstance)\s*\(.*(?:request|param|user|input|args)"#,
        languages: &["java"], cwe: "CWE-470",
        remediation: "Use allowlist for valid class/method names",
        false_positive_hint: "Check if class name is from trusted source",
    },
    VulnRule {
        id: "JAVA-SEC-002", name: "Java JNDI Injection (Log4Shell-style)",
        description: "JNDI lookup with user input — remote code execution",
        category: VulnCategory::Injection, severity: Severity::Critical,
        pattern: r#"(?i)(?:InitialContext\.lookup|ctx\.lookup|JndiTemplate\.lookup)\s*\(.*(?:request|param|user|input|header)"#,
        languages: &["java"], cwe: "CWE-917",
        remediation: "Never pass user input to JNDI lookups. Upgrade Log4j to 2.17.1+",
        false_positive_hint: "Check if JNDI lookup string is user-controlled",
    },
    VulnRule {
        id: "JAVA-SEC-003", name: "Java SpEL Injection",
        description: "Spring Expression Language with user input — RCE",
        category: VulnCategory::Injection, severity: Severity::Critical,
        pattern: r#"(?i)(?:ExpressionParser|SpelExpressionParser).*\.parseExpression\s*\(.*(?:request|param|user|input)"#,
        languages: &["java"], cwe: "CWE-917",
        remediation: "Use SimpleEvaluationContext instead of StandardEvaluationContext",
        false_positive_hint: "Check if expression is user-controlled",
    },
    VulnRule {
        id: "JAVA-SEC-004", name: "Java Open Redirect",
        description: "HTTP redirect using user-controlled URL",
        category: VulnCategory::OpenRedirect, severity: Severity::Medium,
        pattern: r#"(?i)(?:sendRedirect|setHeader\s*\(\s*["']Location["'])\s*\(.*(?:request\.getParameter|request\.getAttribute|param)"#,
        languages: &["java"], cwe: "CWE-601",
        remediation: "Validate redirect URL against allowlist of paths",
        false_positive_hint: "Check if URL is validated",
    },
    VulnRule {
        id: "JAVA-SEC-005", name: "Java Regex DoS",
        description: "User input used in regex Pattern compilation",
        category: VulnCategory::RegexDoS, severity: Severity::Medium,
        pattern: r#"(?i)Pattern\.compile\s*\(.*(?:request|param|user|input|args)"#,
        languages: &["java"], cwe: "CWE-1333",
        remediation: "Validate regex complexity, use timeout, or escape user input",
        false_positive_hint: "Check if pattern is from user input",
    },
    VulnRule {
        id: "JAVA-FILE-001", name: "Java ZIP Slip",
        description: "ZIP entry extraction without path validation — ZIP Slip attack",
        category: VulnCategory::PathTraversal, severity: Severity::High,
        pattern: r#"(?i)(?:ZipEntry|ZipInputStream|ZipFile).*(?:getName|getEntry)"#,
        languages: &["java"], cwe: "CWE-22",
        remediation: "Validate extracted file path starts with destination directory",
        false_positive_hint: "Check if path is validated against directory traversal",
    },
    VulnRule {
        id: "JAVA-LOG-001", name: "Java Log Injection",
        description: "User input logged without sanitization — log forging",
        category: VulnCategory::Injection, severity: Severity::Medium,
        pattern: r#"(?i)(?:logger|log|LOG)\.\w+\s*\(.*(?:request\.getParameter|request\.getHeader|param|user_input)"#,
        languages: &["java"], cwe: "CWE-117",
        remediation: "Sanitize log input: strip newlines and special characters",
        false_positive_hint: "Check if user input is sanitized before logging",
    },
];

// ========================== C/C++ EXTENDED ==========================
pub static C_EXT_RULES: &[VulnRule] = &[
    VulnRule {
        id: "C-MEM-001", name: "C Double Free",
        description: "Potential double free vulnerability",
        category: VulnCategory::UseAfterFree, severity: Severity::Critical,
        pattern: r#"free\s*\(\s*(\w+)\s*\)(?:.*\n)*.*free\s*\(\s*\1\s*\)"#,
        languages: &["c", "cpp"], cwe: "CWE-415",
        remediation: "Set pointer to NULL after free: free(ptr); ptr = NULL;",
        false_positive_hint: "Check if pointer is reassigned between frees",
    },
    VulnRule {
        id: "C-MEM-002", name: "C Null Pointer Dereference",
        description: "Using pointer without null check after allocation",
        category: VulnCategory::BufferOverflow, severity: Severity::High,
        pattern: r#"(?:malloc|calloc|realloc|strdup)\s*\([^)]*\)\s*;"#,
        languages: &["c", "cpp"], cwe: "CWE-476",
        remediation: "Always check allocation return value for NULL",
        false_positive_hint: "Check if null check follows on next line",
    },
    VulnRule {
        id: "C-BUF-001", name: "C Unsafe String Copy",
        description: "Using strcpy/strcat without bounds checking",
        category: VulnCategory::BufferOverflow, severity: Severity::High,
        pattern: r#"\b(?:strcpy|strcat|sprintf|gets|scanf)\s*\("#,
        languages: &["c", "cpp"], cwe: "CWE-120",
        remediation: "Use strncpy/strncat/snprintf with size limits",
        false_positive_hint: "Check if buffer size is guaranteed",
    },
    VulnRule {
        id: "C-RAND-001", name: "C Insecure Random (rand/srand)",
        description: "Using rand() for security — predictable PRNG",
        category: VulnCategory::InsecureRandom, severity: Severity::Medium,
        pattern: r#"\brand\s*\(\s*\).*(?:key|token|secret|password|nonce|salt|seed|iv)"#,
        languages: &["c", "cpp"], cwe: "CWE-338",
        remediation: "Use arc4random(), getrandom(), or /dev/urandom",
        false_positive_hint: "Check if used in security context",
    },
    VulnRule {
        id: "C-SEC-001", name: "C Setuid Without Dropping Privileges",
        description: "Program using setuid but may not dropping privileges",
        category: VulnCategory::PrivilegeEscalation, severity: Severity::High,
        pattern: r#"set(?:uid|euid|gid|egid)\s*\(\s*0\s*\)"#,
        languages: &["c", "cpp"], cwe: "CWE-250",
        remediation: "Drop privileges as early as possible after suid operations",
        false_positive_hint: "Check if privileges are properly dropped",
    },
    VulnRule {
        id: "C-SEC-002", name: "C Unsafe Environment Variable Use",
        description: "Using getenv() result in system-like calls",
        category: VulnCategory::CommandInjection, severity: Severity::High,
        pattern: r#"(?:system|popen|exec[lvpe]*)\s*\(.*getenv\s*\("#,
        languages: &["c", "cpp"], cwe: "CWE-78",
        remediation: "Validate and sanitize environment variable values",
        false_positive_hint: "Check if env var is validated",
    },
];

// ========================== GO EXTENDED ==========================
pub static GO_EXT_RULES: &[VulnRule] = &[
    VulnRule {
        id: "GO-SEC-001", name: "Go Insecure TLS Config",
        description: "TLS InsecureSkipVerify enabled — MITM risk",
        category: VulnCategory::InsecureTLS, severity: Severity::High,
        pattern: r#"InsecureSkipVerify\s*:\s*true"#,
        languages: &["go"], cwe: "CWE-295",
        remediation: "Remove InsecureSkipVerify: true, use proper CA certificates",
        false_positive_hint: "Should only be used in test environments",
    },
    VulnRule {
        id: "GO-SEC-002", name: "Go HTML Template with User Input",
        description: "Using text/template instead of html/template for HTML output",
        category: VulnCategory::XSS, severity: Severity::High,
        pattern: r#"text/template.*\.Execute"#,
        languages: &["go"], cwe: "CWE-79",
        remediation: "Use html/template instead of text/template for HTML output",
        false_positive_hint: "Check if output is HTML",
    },
    VulnRule {
        id: "GO-SEC-003", name: "Go Unhandled Error",
        description: "Error return value ignored - may hide security failures",
        category: VulnCategory::Misconfiguration, severity: Severity::Low,
        pattern: r#"(?i)(?:db\.Exec|http\.ListenAndServe|bcrypt\.CompareHash|jwt\.Parse)\s*\([^)]*\)\s*$"#,
        languages: &["go"], cwe: "CWE-252",
        remediation: "Always check error return values",
        false_positive_hint: "Check if error is handled on next line",
    },
    VulnRule {
        id: "GO-SEC-004", name: "Go Race Condition (goroutine)",
        description: "Shared variable accessed without synchronization in goroutine",
        category: VulnCategory::RaceCondition, severity: Severity::Medium,
        pattern: r#"go\s+func\s*\(\s*\)\s*\{[^}]*(?:append|delete|map\[|slice)"#,
        languages: &["go"], cwe: "CWE-362",
        remediation: "Use sync.Mutex, sync.RWMutex, or channels for goroutine safety",
        false_positive_hint: "Check if proper synchronization exists",
    },
    VulnRule {
        id: "GO-DESER-001", name: "Go Insecure Gob/JSON Deserialization",
        description: "Deserializing untrusted data via gob/encoding",
        category: VulnCategory::InsecureDeserialization, severity: Severity::High,
        pattern: r#"(?i)(?:gob\.NewDecoder|json\.NewDecoder)\s*\(\s*(?:r\.Body|req\.Body|conn)"#,
        languages: &["go"], cwe: "CWE-502",
        remediation: "Validate and limit decoded data, use json.Decoder.DisallowUnknownFields()",
        false_positive_hint: "Check if decoded data is validated",
    },
    VulnRule {
        id: "GO-REDIR-001", name: "Go Open Redirect",
        description: "HTTP redirect using user-controlled URL",
        category: VulnCategory::OpenRedirect, severity: Severity::Medium,
        pattern: r#"(?i)http\.Redirect\s*\(.*(?:r\.(?:FormValue|URL\.Query)|params|query)"#,
        languages: &["go"], cwe: "CWE-601",
        remediation: "Validate redirect URL against allowlist",
        false_positive_hint: "Check if URL is validated",
    },
];

// ========================== PHP EXTENDED ==========================
pub static PHP_EXT_RULES: &[VulnRule] = &[
    VulnRule {
        id: "PHP-SEC-001", name: "PHP session_start without secure flags",
        description: "Session started without secure configuration",
        category: VulnCategory::Misconfiguration, severity: Severity::Medium,
        pattern: r#"session_start\s*\(\s*\)"#,
        languages: &["php"], cwe: "CWE-614",
        remediation: "Configure session with: session.cookie_secure=1, session.cookie_httponly=1, session.cookie_samesite=Strict",
        false_positive_hint: "Check if session config is set elsewhere",
    },
    VulnRule {
        id: "PHP-SEC-002", name: "PHP extract() on User Input",
        description: "extract() on user data overwrites variables — mass assignment",
        category: VulnCategory::MassAssignment, severity: Severity::Critical,
        pattern: r#"extract\s*\(\s*\$_(?:GET|POST|REQUEST|COOKIE)"#,
        languages: &["php"], cwe: "CWE-915",
        remediation: "Never use extract() on user input. Use specific variable access",
        false_positive_hint: "extract() with EXTR_SKIP flag is safer",
    },
    VulnRule {
        id: "PHP-SEC-003", name: "PHP File Upload Vulnerability",
        description: "File upload without proper validation",
        category: VulnCategory::InsecureFileOps, severity: Severity::High,
        pattern: r#"(?i)move_uploaded_file\s*\(.*\$_FILES.*\$_(?:GET|POST|REQUEST)"#,
        languages: &["php"], cwe: "CWE-434",
        remediation: "Validate file type, extension, size; store outside web root",
        false_positive_hint: "Check if file validation exists",
    },
    VulnRule {
        id: "PHP-SEC-004", name: "PHP Type Juggling",
        description: "Loose comparison (==) for security checks — type juggling attack",
        category: VulnCategory::BrokenAuth, severity: Severity::High,
        pattern: r#"(?i)(?:password|token|hash|secret|key)\s*==\s*\$"#,
        languages: &["php"], cwe: "CWE-697",
        remediation: "Use strict comparison (===) or hash_equals() for security checks",
        false_positive_hint: "Check if loose comparison is intentional",
    },
    VulnRule {
        id: "PHP-SEC-005", name: "PHP Unsafe preg_replace /e",
        description: "preg_replace with /e modifier — code execution",
        category: VulnCategory::Injection, severity: Severity::Critical,
        pattern: r#"preg_replace\s*\(\s*["']/.*?/e["']"#,
        languages: &["php"], cwe: "CWE-94",
        remediation: "Use preg_replace_callback() instead of /e modifier",
        false_positive_hint: "The /e modifier was removed in PHP 7.0",
    },
    VulnRule {
        id: "PHP-CORS-001", name: "PHP CORS Wildcard",
        description: "CORS Access-Control-Allow-Origin set to wildcard",
        category: VulnCategory::Misconfiguration, severity: Severity::Medium,
        pattern: r#"(?i)header\s*\(\s*["']Access-Control-Allow-Origin:\s*\*"#,
        languages: &["php"], cwe: "CWE-942",
        remediation: "Restrict CORS to specific trusted origins",
        false_positive_hint: "May be valid for public APIs",
    },
];

// ========================== RUBY EXTENDED ==========================
pub static RUBY_EXT_RULES: &[VulnRule] = &[
    VulnRule {
        id: "RB-SEC-001", name: "Ruby send() with User Input",
        description: "Dynamic method call using user input — arbitrary method invocation",
        category: VulnCategory::Injection, severity: Severity::Critical,
        pattern: r#"(?i)\.send\s*\(\s*(?:params|request|user_input)"#,
        languages: &["rb"], cwe: "CWE-470",
        remediation: "Use allowlist for valid method names",
        false_positive_hint: "Check if method name is from user input",
    },
    VulnRule {
        id: "RB-SEC-002", name: "Ruby constantize with User Input",
        description: "Dynamic class loading from user input — code execution",
        category: VulnCategory::Injection, severity: Severity::Critical,
        pattern: r#"(?i)(?:constantize|safe_constantize|classify\.constantize).*(?:params|request|user)"#,
        languages: &["rb"], cwe: "CWE-470",
        remediation: "Use allowlist for valid class names",
        false_positive_hint: "Check if class name is from user input",
    },
    VulnRule {
        id: "RB-SEC-003", name: "Rails render inline with User Input",
        description: "Inline template rendering with user data — SSTI",
        category: VulnCategory::TemplateInjection, severity: Severity::Critical,
        pattern: r#"(?i)render\s+inline\s*:.*(?:params|request|user)"#,
        languages: &["rb"], cwe: "CWE-1336",
        remediation: "Never use render inline with user input. Use proper templates",
        false_positive_hint: "Check if input reaches template",
    },
    VulnRule {
        id: "RB-SEC-004", name: "Rails Mass Assignment",
        description: "Model creation/update with unsanitized params",
        category: VulnCategory::MassAssignment, severity: Severity::High,
        pattern: r#"(?i)(?:\.create|\.update|\.new)\s*\(\s*params"#,
        languages: &["rb"], cwe: "CWE-915",
        remediation: "Use strong parameters: params.require(:model).permit(:fields)",
        false_positive_hint: "Check if params are permitted",
    },
    VulnRule {
        id: "RB-AUTH-001", name: "Rails skip_before_action Authentication",
        description: "Skipping authentication filter — unauthenticated access",
        category: VulnCategory::BrokenAuth, severity: Severity::High,
        pattern: r#"(?i)skip_before_(?:action|filter)\s+:(?:authenticate|require_login|verify_auth)"#,
        languages: &["rb"], cwe: "CWE-306",
        remediation: "Use only: or except: to limit which actions skip authentication",
        false_positive_hint: "May be intentional for public pages",
    },
];

// ========================== RUST EXTENDED ==========================
pub static RUST_EXT_RULES: &[VulnRule] = &[
    VulnRule {
        id: "RS-SEC-001", name: "Rust unwrap() on User Input",
        description: "unwrap() on potentially invalid user input — panic risk",
        category: VulnCategory::Misconfiguration, severity: Severity::Medium,
        pattern: r#"(?i)(?:from_str|parse|to_string|into|try_into)\s*\(\s*\)\s*\.unwrap\(\)"#,
        languages: &["rs"], cwe: "CWE-248",
        remediation: "Use ? operator or match/unwrap_or_else for error handling",
        false_positive_hint: "unwrap in tests is acceptable",
    },
    VulnRule {
        id: "RS-SEC-002", name: "Rust Transmute Unsafe",
        description: "std::mem::transmute — type punning, UB risk",
        category: VulnCategory::BufferOverflow, severity: Severity::High,
        pattern: r#"(?:std::mem::)?transmute\s*[:<]"#,
        languages: &["rs"], cwe: "CWE-843",
        remediation: "Use safe alternatives: From/Into traits, as casts, or TryFrom",
        false_positive_hint: "May be needed for FFI interop",
    },
    VulnRule {
        id: "RS-SEC-003", name: "Rust Raw Pointer Dereference",
        description: "Dereferencing raw pointer — memory safety risk",
        category: VulnCategory::UseAfterFree, severity: Severity::High,
        pattern: r#"\*(?:mut|const)\s+\w+.*(?:as\s+\*(?:mut|const)|\*\w+)"#,
        languages: &["rs"], cwe: "CWE-119",
        remediation: "Minimize raw pointer usage, keep unsafe blocks small and well-documented",
        false_positive_hint: "May be necessary for FFI",
    },
];

// ========================== C# EXTENDED ==========================
pub static CSHARP_EXT_RULES: &[VulnRule] = &[
    VulnRule {
        id: "CS-SEC-001", name: "C# ViewState Tampering",
        description: "ViewState MAC validation disabled",
        category: VulnCategory::Misconfiguration, severity: Severity::High,
        pattern: r#"(?i)EnableViewStateMac\s*=\s*["']?false"#,
        languages: &["cs"], cwe: "CWE-642",
        remediation: "Set EnableViewStateMac to true",
        false_positive_hint: "Always keep ViewState MAC enabled",
    },
    VulnRule {
        id: "CS-SEC-002", name: "C# Request Validation Disabled",
        description: "ASP.NET request validation disabled — XSS risk",
        category: VulnCategory::XSS, severity: Severity::High,
        pattern: r#"(?i)(?:ValidateInput\s*\(\s*false\)|validateRequest\s*=\s*["']false)"#,
        languages: &["cs"], cwe: "CWE-79",
        remediation: "Keep request validation enabled, use [AllowHtml] only where needed",
        false_positive_hint: "May be needed for rich text editors",
    },
    VulnRule {
        id: "CS-SEC-003", name: "C# Hardcoded Connection String",
        description: "Database connection string with credentials hardcoded",
        category: VulnCategory::HardcodedSecret, severity: Severity::High,
        pattern: r#"(?i)(?:connectionString|ConnectionString)\s*=\s*["'].*(?:Password|Pwd)\s*=\s*[^;$\{]{4,}"#,
        languages: &["cs"], cwe: "CWE-798",
        remediation: "Use app settings, Azure Key Vault, or secrets manager",
        false_positive_hint: "Check if connection string is from configuration",
    },
    VulnRule {
        id: "CS-DESER-001", name: "C# BinaryFormatter Deserialization",
        description: "BinaryFormatter deserialization — RCE vector",
        category: VulnCategory::InsecureDeserialization, severity: Severity::Critical,
        pattern: r#"(?i)(?:BinaryFormatter|SoapFormatter|LosFormatter|ObjectStateFormatter|NetDataContractSerializer).*Deserialize"#,
        languages: &["cs"], cwe: "CWE-502",
        remediation: "Use System.Text.Json or JsonSerializer instead",
        false_positive_hint: "BinaryFormatter is deprecated in .NET 5+",
    },
    VulnRule {
        id: "CS-CRYPTO-001", name: "C# Weak Crypto Algorithm",
        description: "Using deprecated cryptographic algorithm (DES, RC2, MD5)",
        category: VulnCategory::WeakCrypto, severity: Severity::Medium,
        pattern: r#"(?i)(?:DESCryptoServiceProvider|RC2CryptoServiceProvider|TripleDESCryptoServiceProvider|MD5CryptoServiceProvider|SHA1CryptoServiceProvider|RijndaelManaged)\.Create"#,
        languages: &["cs"], cwe: "CWE-327",
        remediation: "Use Aes.Create() for encryption, SHA256/SHA512 for hashing",
        false_positive_hint: "Check if used for security purposes",
    },
];

// ========================== SWIFT/MOBILE EXTENDED ==========================
pub static MOBILE_EXT_RULES: &[VulnRule] = &[
    VulnRule {
        id: "MOB-SEC-001", name: "iOS ATS Disabled",
        description: "App Transport Security disabled — allows insecure HTTP",
        category: VulnCategory::InsecureTLS, severity: Severity::High,
        pattern: r#"NSAllowsArbitraryLoads.*true"#,
        languages: &["swift", "xml"],  cwe: "CWE-319",
        remediation: "Enable ATS: set NSAllowsArbitraryLoads to false",
        false_positive_hint: "May be needed for specific legacy domains",
    },
    VulnRule {
        id: "MOB-SEC-002", name: "Android WebView JavaScript Enabled",
        description: "WebView with JavaScript enabled and addJavascriptInterface — RCE on old Android",
        category: VulnCategory::Injection, severity: Severity::High,
        pattern: r#"(?i)(?:setJavaScriptEnabled\s*\(\s*true\)|addJavascriptInterface)"#,
        languages: &["java", "kt"], cwe: "CWE-749",
        remediation: "Use @JavascriptInterface annotation, set targetSdkVersion >= 17",
        false_positive_hint: "Check if WebView content is trusted",
    },
    VulnRule {
        id: "MOB-SEC-003", name: "Android Exported Component",
        description: "Android component exported without permission control",
        category: VulnCategory::BrokenAuth, severity: Severity::Medium,
        pattern: r#"(?i)android:exported\s*=\s*["']true["']"#,
        languages: &["xml"], cwe: "CWE-926",
        remediation: "Set android:exported=false or add android:permission",
        false_positive_hint: "May be intentional for launcher activities",
    },
    VulnRule {
        id: "MOB-SEC-004", name: "iOS Keychain Without Access Control",
        description: "Keychain item stored without biometric/passcode protection",
        category: VulnCategory::InsecureFileOps, severity: Severity::Medium,
        pattern: r#"(?i)SecItemAdd.*(?:kSecAttrAccessible.*(?:Always|AfterFirstUnlock))"#,
        languages: &["swift"], cwe: "CWE-922",
        remediation: "Use kSecAttrAccessibleWhenUnlockedThisDeviceOnly with access control",
        false_positive_hint: "Check sensitivity of stored data",
    },
    VulnRule {
        id: "MOB-SEC-005", name: "Android Debug Flag",
        description: "Android debuggable flag enabled",
        category: VulnCategory::Misconfiguration, severity: Severity::High,
        pattern: r#"(?i)android:debuggable\s*=\s*["']true["']"#,
        languages: &["xml"], cwe: "CWE-489",
        remediation: "Set android:debuggable=false in production builds",
        false_positive_hint: "Should be false in release builds",
    },
];

// ========================== SHELL SCRIPT RULES ==========================
pub static SHELL_RULES: &[VulnRule] = &[
    VulnRule {
        id: "SH-INJ-001", name: "Shell Command Injection via Variable",
        description: "Unquoted variable in command — injection vector",
        category: VulnCategory::CommandInjection, severity: Severity::High,
        pattern: r#"(?:eval|exec|system|xargs)\s+.*\$\{?\w+\}?(?:[^"']|$)"#,
        languages: &["sh", "bash", "zsh"], cwe: "CWE-78",
        remediation: "Always quote variables: \"$var\" and use arrays for commands",
        false_positive_hint: "Check if variable is from user input",
    },
    VulnRule {
        id: "SH-SEC-001", name: "Shell Curl Pipe to Shell",
        description: "Downloading and executing script in one step — supply chain risk",
        category: VulnCategory::CommandInjection, severity: Severity::High,
        pattern: r#"(?:curl|wget)\s+.*\|\s*(?:sudo\s+)?(?:bash|sh|zsh)"#,
        languages: &["sh", "bash", "zsh"], cwe: "CWE-829",
        remediation: "Download, verify checksum, then execute separately",
        false_positive_hint: "Check if URL is from trusted source",
    },
    VulnRule {
        id: "SH-SEC-002", name: "Shell World-Writable File Creation",
        description: "Creating file with world-writable permissions",
        category: VulnCategory::InsecureFileOps, severity: Severity::Medium,
        pattern: r#"chmod\s+(?:777|666|o\+w)"#,
        languages: &["sh", "bash", "zsh"], cwe: "CWE-732",
        remediation: "Use restrictive permissions: chmod 600 or chmod 700",
        false_positive_hint: "Check if broad permissions are necessary",
    },
    VulnRule {
        id: "SH-SEC-003", name: "Shell Temporary File Predictable Name",
        description: "Using predictable temp file name — race condition risk",
        category: VulnCategory::RaceCondition, severity: Severity::Medium,
        pattern: r#"(?:/tmp/\w+|tempfile=\$\w+)"#,
        languages: &["sh", "bash", "zsh"], cwe: "CWE-377",
        remediation: "Use mktemp for secure temporary files",
        false_positive_hint: "Check if mktemp is used instead",
    },
];

pub fn all_extended_rules() -> Vec<&'static VulnRule> {
    let mut rules: Vec<&'static VulnRule> = Vec::new();
    for r in PYTHON_EXT_RULES { rules.push(r); }
    for r in JS_EXT_RULES { rules.push(r); }
    for r in JAVA_EXT_RULES { rules.push(r); }
    for r in C_EXT_RULES { rules.push(r); }
    for r in GO_EXT_RULES { rules.push(r); }
    for r in PHP_EXT_RULES { rules.push(r); }
    for r in RUBY_EXT_RULES { rules.push(r); }
    for r in RUST_EXT_RULES { rules.push(r); }
    for r in CSHARP_EXT_RULES { rules.push(r); }
    for r in MOBILE_EXT_RULES { rules.push(r); }
    for r in SHELL_RULES { rules.push(r); }
    rules
}
